#!/usr/bin/env bash

# adapted from https://gist.github.com/1643715

for i in $(find $HOME/.sbt/boot/scala-2.9.1/org.scala-tools.sbt/sbt/0.11.2/compiler-interface-src -name 'compiler-interface-src-0.11.*.jar'); do
  t="${i%.jar}-tmp"
  echo $t
  unzip $i -d $t
  cd $t
  sed -i API.scala -e 's/sym.isLocalClass || sym.isAnonymousClass || sym.fullName.endsWith(LocalChild)/sym.isLocalClass || sym.isAnonymousClass || sym.fullName.endsWith(LocalChild.toString)/g'
  rm $i
  zip -r $i .
  cd ..
  rm -rf $t
done
